<?php

namespace Xtdb;

use Illuminate\Database\Query\Builder;
use Illuminate\Database\Query\Grammars\PostgresGrammar;

/** Prototype grammar: only the overrides the scenarios showed necessary. */
class XtdbGrammar extends PostgresGrammar
{
    // No RETURNING: the id is generated by the client (see XtdbProcessor).
    public function compileInsertGetId(Builder $query, $values, $sequence)
    {
        return $this->compileInsert($query, $values);
    }

    // No FOR UPDATE / FOR SHARE.
    protected function compileLock(Builder $query, $value)
    {
        return '';
    }

    // No ILIKE.
    protected function whereLike(Builder $query, $where)
    {
        $where['operator'] = $where['not'] ? 'not like' : 'like';

        return $where['caseSensitive']
            ? $this->wrap($where['column']).' '.$where['operator'].' '.$this->parameter($where['value'])
            : 'lower('.$this->wrap($where['column']).') '.$where['operator'].' lower('.$this->parameter($where['value']).')';
    }

    // Nested fields: (col).key.sub instead of col->>'key'.
    protected function wrapJsonSelector($value)
    {
        [$field, $path] = $this->wrapJsonFieldAndPath($value);
        $segments = array_map(fn ($s) => '"'.trim($s, "'\"").'"', array_filter(explode('.', ltrim($path, '.'))));

        return '('.$field.').'.implode('.', $segments);
    }

    public function compileTruncate(Builder $query)
    {
        return ['erase from '.$this->wrapTable($query->from).' where true' => []];
    }
}
